### ISSUE TITLE
Property `Creation Date` always return current date instead of the stored one

### ISSUE THREAD

**Issue by sebbousquet** [gisaia/ARLAS-persistence#11]
**_Data in DB_**
![Capture d’écran 2020-05-12 à 17 40 31](https://user-images.githubusercontent.com/7236202/81714965-f3c4c700-9477-11ea-999d-f5cf1c428e37.png)

**_Result of curl command_**
![Capture d’écran 2020-05-12 à 17 40 05](https://user-images.githubusercontent.com/7236202/81715081-12c35900-9478-11ea-94e4-a9c8c1e369e5.png)

**_Convertion timestamp to human readable date_**
![Capture d’écran 2020-05-12 à 17 44 14](https://user-images.githubusercontent.com/7236202/81715195-38e8f900-9478-11ea-906b-f1219bdecfff.png)

**Comment by alainbodiguel** [comment]
What is the curl command that you're executing ?

**Comment by sebbousquet** [comment]
> What is the curl command that you're executing ?

```
curl -X GET "http://localhost:19997/arlas_persistence_server/persistence?type=objecttype&size=10&page=1&order=desc&pretty=false" -H "accept: application/json;charset=utf-8" -H "X-forwarded-User:MyToken"
```

**Comment by sebbousquet** [comment]
@alainbodiguel error also occurs on endpoint `/persistence/{id}`
